#!/bin/sh

# This  is an ugly hack for partial updating of build environment from
# Ubuntu 12.04 (Precise Pangolin) to Ubuntu 14.04 (Trusty Tahr):
sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list
sudo apt-get update -qq

if [ "$QT_SELECT" = "qt4" ]; then
    sudo apt-get install -qq libqt4-dev
else
    sudo apt-get install -qq qtbase5-dev
fi

case "$CONFIG" in
full*)
    sudo apt-get install -qq  doxygen libopus-dev libspeex-dev libtheora-dev libvpx-dev
    ;;
esac
